### ISSUE TITLE
Upload in "high quality" for unlimited storage

### ISSUE THREAD

**Issue by simonedegiacomi** [nmrshll/gphotos-uploader-cli#10]
I 'd like to help with the client side compression, to allow users to upload unlimited photos.
Have you already started working on it?

To add this feature we would definitely need an option in the configuration of the cli to allow the users to enable/disable the compression, but where do you think it's better to implement the compression? in the cli o directly on the library?

**Comment by ledlamp** [comment]
Oh no, so photos uploaded with this CLI will count against quota, regardless of the account's setting? 😟

**Comment by ledlamp** [comment]
Yep it does. Oh well, at least I can use the `Recover Storage` button in Google Photos.

But is it even possible for this program to upload as “High Quality”?

From API documentation:
[![image](https://user-images.githubusercontent.com/24686877/45378159-8d581900-b5b1-11e8-9151-7746941c71c5.png)](https://developers.google.com/photos/library/guides/api-limits-quotas)

**Comment by simonedegiacomi** [comment]
I've seen that too in the documentation... so downsizing the image is not a solution.
As I already reported in [this issue](https://github.com/simonedegiacomi/gphotosuploader/issues/23), there is [this feature request](https://issuetracker.google.com/issues/111193036) in the official Google Photos API issues page.

**Comment by Lyve1981** [comment]
Did anyone checkout the website photos.google.com and checked the API that is used there? The URLs look slightly different, but still quite similar to the official API. I'd assume that it is somehow possible to upload in high quality, but it is just not documented?

**Comment by psyciknz** [comment]
Or had a look at the google photos uploader/sync program to see how it does it?

**Comment by nhorvath** [comment]
Last I checked there is no way to upload in the "high quality" (unlimited) via the API. It's a future feature on the google side. The google apps use a non public api.
