### ISSUE TITLE
Config did not generate

### ISSUE THREAD

**Issue by ledlamp** [nmrshll/gphotos-uploader-cli#11]
Set up was a bit rough.

First, after installation with `go get -u github.com/nmrshll/gphotos-uploader-cli`, neither `gphotos-uploader-cli` nor `gphotos-uploader` was found; it did not install globally. I had to use `~/go/bin/gphotos-uploader-cli`.

Second, it said it generated a config file at `~/.config/gphotos-uploader-cli/config.hjson`, but it did not. I had to copy the example and create it manually.

Besides that, setup went quite smoothly and I am up and running, uploading my automated (5sec interval) screenshots to an alternative account 😄

**Comment by nmrshll** [comment]
Thanks for the feedback. I'll try to find why it didn't copy the file.

For the setup process, there's only so much I can do with `go get`.
I'll start working on other hopefully easier install options, and I might be able to create the config file at setup.

**Comment by barkside** [comment]
Yes I found this too. Looks like the folder ~/.config/gphotos-uploader-cli did not get created - perhaps a mkdir -p is required?

**Comment by nhorvath** [comment]
I can confirm that the folder must exist, then it will create the example file.
