### ISSUE TITLE
Oath files

### ISSUE THREAD

**Issue by nwhistler** [nmrshll/gphotos-uploader-cli#17]
I am looking at making this a docker container and am looking for the file or files it saves when you do the Oath authentication piece locally. I am wondering if I can create a container and simply copy that in to bypass having to open a browser and authenticate the application. That still might be possible in docker, but I'd rather not have to get that complicated.

Then end goal is to run this container directly on my storage to periodically check if that directory is in sync with google photos.

Any ideas?

Thanks,

Nate

**Comment by nwhistler** [comment]
Nevermind, doesn't look like it's going to be as easy as I hoped.

**Comment by rfgamaral** [comment]
@nwhistler Have you managed to dockerize this? I've been thinking about doing the same thing...
