### ISSUE TITLE
Issue running this on Windows

### ISSUE THREAD

**Issue by sledge1977** [nmrshll/gphotos-uploader-cli#18]
Hi, I tried running this tool on Windows 10 64bit, but I'm running into issues with the configuration file.It seems that characters like : are not allowed, but are necessary on Windows to give an absoulte Path to a Folder.

**Comment by pacoorozco** [comment]
Why are not you using the Windows client? I think this project it's focusing in having a linux CLI.

**Comment by sledge1977** [comment]
I do not want to install the Backup and Sync Client from Google, because it brings to much overhead. I only want to upload my Pictures to Google Photos. Would be nice to have a small tool like this for this task.

**Comment by antonmos** [comment]
i would like to run it on windows cuz "Backup and Sync Client from Google" doesnt create albums

**Comment by pacoorozco** [comment]
Hi @antonmos 

There are a lot of issues to be done before getting `gphotos-uploader-cli`working in Windows... but contributions are welcomed :-D
