### ISSUE TITLE
oauth on each run

### ISSUE THREAD

**Issue by wormiedk** [nmrshll/gphotos-uploader-cli#37]
I am running gphotos-uploader-cli on MacOS. For some reason I need to do the oauth each time I run the client. Where should the program store the accepted oauth token?

**Comment by rfgamaral** [comment]
@calisro Does that mean that `gphotos-uploader-cli` currently doesn't implement the "refresh token" mechanism?

**Comment by pacoorozco** [comment]
Yes It's confirmed... `ghpotos-uploader-cli` is not using `refresh token`. We are working on it at #103 

Let's continue there @wormiedk @calisro and @rfgamaral
