### ISSUE TITLE
Videos don't delete

### ISSUE THREAD

**Issue by Mason10198** [nmrshll/gphotos-uploader-cli#42]
Super simple, but I can't even tell if the functionality is there...
Can videos be set to delete after upload? I have delete after upload set to true, but the CLI output just says it's skipping the file because it's not an image.

**Comment by nmrshll** [comment]
Yes, until now it was only checking for images that they were correctly uploaded, so deleting only images.

I just added the same for gifs and videos, but it will certainly need more testing
