### ISSUE TITLE
Can't use on Terminal

### ISSUE THREAD

**Issue by esmocode** [nmrshll/gphotos-uploader-cli#46]
Hi 
I want to use this on Ubuntu server (non Desktop GUI) and when i run ./gphotos-uploader-cli this is the error i get, i was wondering is there a way to use this on terminal version ? or how about opening it on desktop and copying the authentication files to certain folder ?

2019/02/15 10:05:07 Need to log login into account esmodev@gmail.com
2019/02/15 10:05:08 You will now be taken to your browser for authentication
2019/02/15 10:05:10 failed authenticating new client: all options failed with errors:
 --- at /root/go/src/github.com/nmrshll/google-photos-api-client-go/noserver-gphotos/no-server.go:37 (NewClient) ---
Caused by: 1 error occurred:
        * failed authenticating user
 --- at /root/go/src/github.com/nmrshll/google-photos-api-client-go/noserver-gphotos/no-server.go:70 (AuthenticateUser.func1) ---
Caused by: failed opening browser window
 --- at /root/go/src/github.com/nmrshll/oauth2-noserver/oauth2ns.go:90 (AuthenticateUser) ---
Caused by: exit status 3

**Comment by JosPolfliet** [comment]
Related: storing info in the keyring doesn't work on headless servers unless you install gnome-keyring and run in the proper dbus session. See https://github.com/jaraco/keyring/blob/master/README.rst#id16

**Comment by hnjoshi** [comment]
I am facing same issue

**Comment by schoolsplay** [comment]
The first time it starts a browser for you to login and agree to giving access to your stuff by the creds you created (Oauth consent screen)
After that you can use it in a terminal.
If I remember correctly from the Oauth setup, after 40 times you will be asked again for consent.
Perhaps you can get it working with the lynx text browser.

**Comment by pacoorozco** [comment]
It's the same issue than #15.

Closing it as duplicated
