### ISSUE TITLE
Raw support

### ISSUE THREAD

**Issue by mdjaere** [nmrshll/gphotos-uploader-cli#48]
Thanks for a great project!

Since Google Photos supports a [range of raw files](https://support.google.com/photos/answer/6193313), it would be great if the uploader supported them too.

Using @rfgamaral's docker [implementation ](https://hub.docker.com/r/rfgamaral/gphotos-uploader) from [issue 15](https://github.com/nmrshll/gphotos-uploader-cli/issues/15), the uploader skips my raw files. I assume it is a limitation with this repo.

**Comment by tonymet** [comment]
from the api docs currently only these formats are supported
```

BMP | JPG
-- | --
GIF | TIFF
ICO | WEBP

```

could you test the api and see if raw (e.g. NEF) can be uploaded? Often api changes are made and not yet documented.  If you find NEF is working, we can implement

**Comment by tonymet** [comment]
@mdjaere any updates? it would be nice to test this and get it working

**Comment by pacoorozco** [comment]
Solved on v0.4.0+
