### ISSUE TITLE
Erasing media from remote 

### ISSUE THREAD

**Issue by amatmv** [nmrshll/gphotos-uploader-cli#54]
Maybe i'm wrong but the uploader does not delete photos from remote if they do not exist in local, does not it?
The uploader could check if a remote file exists locally and if it does not: delete it. Otherwise I have a bunch of photos remotely that i uploaded sometime and i don't want to delete it manually.

**Comment by tonymet** [comment]
unfortunately we can't build the intersection between the destination and the source.  So it would be too risky to try to delete images.  the uploader only adds new ones.

**Comment by amatmv** [comment]
What do you mean by "intersection"? 
Maybe it could be added but under user's responsability.

**Comment by tonymet** [comment]
I mean identifying the files that exist locally and on the server , and
then deleting those that don't -- this part is impractical and dangerous

**Comment by pacoorozco** [comment]
I agree with @tonymet It's too risky. I've labelled as `wontfix`. *Do you disagree?*

**Comment by amatmv** [comment]
@pacoorozco as you want. Thank you anyway! @tonymet
