### ISSUE TITLE
Powershell don't find gphotos-uploader-cli

### ISSUE THREAD

**Issue by stephane-archer** [nmrshll/gphotos-uploader-cli#58]
after `go get -u github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli` if I type `gphotos-uploader-cli` I have the following message:
```
gphotos-uploader-cli : The term 'gphotos-uploader-cli' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ gphotos-uploader-cli
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (gphotos-uploader-cli:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

How can I fix this so I can use the program I just install?

**Comment by pacoorozco** [comment]
Hi @stephane-archer 

It doesn't seem a application error. Probably your `GOPATH` is not set as `PATH` in your Windows... 

I suggest you follow [this guide](https://www.freecodecamp.org/news/setting-up-go-programming-language-on-windows-f02c8c14e2f/).
