### ISSUE TITLE
Allow uploading of anything that Google Photos allows

### ISSUE THREAD

**Issue by avidrissman** [nmrshll/gphotos-uploader-cli#59]
(FYI, I'm using rfgamaral/docker-gphotos-uploader who wraps this.)

I have ARW files and gphotos-uploader-cli is saying:

not a supported image or video: /photos/2012/0703 Scandinavia-Copenhagen to Gothenburg/DSC02006.ARW: skipping file...

etc.

But if I drop those ARW files onto the web UI they upload. Can gphotos-uploader-cli be fixed to upload anything that Google Photos allows?

**Comment by avidrissman** [comment]
It also seems to not be uploading .mts and .mov files. Can there be more flexibility there too?

**Comment by pdecat** [comment]
Upgrading to https://github.com/h2non/filetype/releases/tag/v1.0.8 should help (currently on v1.0.5).
Especially for .mov files:  https://github.com/h2non/filetype/commit/053ef9d780cf7918c2e8a99a728bbc8bb7bc8382

**Comment by avidrissman** [comment]
I'll pass on the note to rfgamaral/docker-gphotos-uploader which wraps this.

Will upgrading to 1.0.8 of filetype help with .heic? They're not showing as images.

**Comment by pacoorozco** [comment]
Hi @avidrissman 

Can you confirm that is working on version 0.1.18+?

**Comment by avidrissman** [comment]
I use this through a docker container; I posted a request to update the docker image at https://github.com/rfgamaral/docker-gphotos-uploader/issues/6 . Also, as per #64 here, uploading broke sometime in the past week or so, so I cannot do testing.

The fact that you do prescreening is IMO the wrong approach. I think there should be a mode to try to upload everything. I filed for that in #66, which would solve this and #65 too.

**Comment by avidrissman** [comment]
rfgamaral just updated his docker container. It’s still failing to upload .mts, .arw, .nef files. There doesn’t seem to be any improvement here for me.

**Comment by avidrissman** [comment]
Ah, .heic works now.

**Comment by pacoorozco** [comment]
We can continue with #66 I think it's the good approach... trying to sync new allowed formats with `h2non` makes not sense :sweat:
