### ISSUE TITLE
Mismatch between types allowed by h2non/filetype and Google Photos

### ISSUE THREAD

**Issue by avidrissman** [nmrshll/gphotos-uploader-cli#65]
Repro:

1. Have a .3gp file; try to upload it
2. h2non/filetype reckons it as a video file so gphotos-uploader-cli attempts to upload it
3. Google Photos doesn't see it as a video file and rejects it
4. gphotos-uploader-cli grinds to a halt.

gphotos-uploader-cli should not be halting if it tried to upload a file that was rejected due to it being an unsupported format. It should mark that in the database and move on.

**Comment by pacoorozco** [comment]
Solved in v0.4.0+
