### ISSUE TITLE
Are the README instructions to compile ourselves correct?

### ISSUE THREAD

**Issue by rfgamaral** [nmrshll/gphotos-uploader-cli#72]
This is the current README.md:

![image](https://user-images.githubusercontent.com/96476/60021947-d2ee5a00-968a-11e9-9084-717f02798eb7.png)

But `github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli` doesn't exist anymore. 

Shouldn't the command now be:

`$ go get -u github.com/nmrshll/gphotos-uploader-cli`

?

**Comment by pacoorozco** [comment]
You're right @rfgamaral and #53 doesn't allow installation with `go get`.

**Comment by rfgamaral** [comment]
So, what's the proper way to install with `go get`?
