### ISSUE TITLE
Multithreading puts files in the wrong albums

### ISSUE THREAD

**Issue by avidrissman** [nmrshll/gphotos-uploader-cli#80]
I upload from a Docker image from my Synology, which means that there are `@eaDir` directories all over the place. Sigh. But the files in there are filtered out as not images, that shouldn’t matter, but it does.

Here’s a log from a session:

```
2019/06/30 01:16:52 Entering Directory: /photos/2019/0616 Washer shelving
2019/06/30 01:16:53 CCVA5551.JPG uploaded successfully as xxxxxxxxxx
2019/06/30 01:16:53 Marked as uploaded: /photos/2019/0612 xxxxxxxxxx
2019/06/30 01:16:53 IMG_6132.MOV uploaded successfully as xxxxxxxxxx
2019/06/30 01:16:53 Marked as uploaded: /photos/2019/0609 xxxxxxxxxx
2019/06/30 01:16:54 using album: 0616 Washer shelving / Id: xxxxxxxxxx
2019/06/30 01:16:54 not a media file: /photos/2019/0616 Washer shelving/.DS_Store: skipping file...
2019/06/30 01:16:54 Entering Directory: /photos/2019/0616 Washer shelving/@eaDir
2019/06/30 01:16:55 xxxxxxxxxx uploaded successfully as xxxxxxxxxx
2019/06/30 01:16:55 Marked as uploaded: /photos/2019/0614 xxxxxxxxxx
2019/06/30 01:16:58 using album: @eaDir / Id: xxxxxxxxxx
2019/06/30 01:16:58 not a media file: /photos/2019/0616 Washer shelving/@eaDir/.DS_Store@SynoResource: skipping file...
2019/06/30 01:16:58 not a media file: /photos/2019/0616 Washer shelving/IMG_6144.AAE: skipping file...
2019/06/30 01:16:58 Uploading IMG_6144.JPG
2019/06/30 01:16:58 Uploading IMG_6145.JPG
2019/06/30 01:16:58 Uploading IMG_6146.JPG
2019/06/30 01:16:58 Uploading IMG_E6144.JPG
```

(Some items are redacted.)

There is a folder, `/photos/2019/0616 Washer shelving` that has four .jpg files in it. It also has a `@eaDir` directory in it. What seems to have happened is that the uploader created an album named `0616 Washer shelving`, then one named `@eaDir`, and then managed to confusedly drop the four images that were in the parent directory into the album named after the child directory.

I was able to catch this because this was a small batch, but this is something that should be fixed.

**Comment by pacoorozco** [comment]
Can you confirm it's failing @avidrissman?

It should be fixed by:

https://github.com/nmrshll/gphotos-uploader-cli/commit/56d4938a2f2b91718fd196590cbe2c4161220509#diff-ffe9c370dd521ec200ef136bd4cfb81cL105

**Comment by avidrissman** [comment]
Not sure how to confirm.

When I update my config and get it working again, I’m going to exclude the `@eaDir` folders, and since I don’t nest folders in folders, I don’t have a structure that will expose this issue if it still exists.

**Comment by pacoorozco** [comment]
As far as you don't have the problem I think we can close this issue
