### ISSUE TITLE
New gnome keyring store created on each launch

### ISSUE THREAD

**Issue by pdecat** [nmrshll/gphotos-uploader-cli#97]
**Describe the bug**

On each launch, a new gnome keyring store is created.

This prevents reusing the previously stored token.

**To Reproduce**

1. leave secret backend type unconfigured (log output: `[keyring] Considering backends: [secret-service kwallet pass file]`)
2. launch `gphotos-uploader-cli` once
3. proceed through OAuth then enter new keyring password when prompted with `Choose password for new keyring` (description: `An application wants to create a new keyring called "googlephotos-uploader-go-api". Choose the password you may to use for it.`) 
4. wait for `gphotos-uploader-cli` execution to complete
5. re-launch `gphotos-uploader-cli`
6. you're once again asked to proceed through OAuth and create a new keyring.

**Expected behavior**

`gphotos-uploader-cli` should reuse existing keyring.

**Screenshots**

![image](https://user-images.githubusercontent.com/318490/62005233-8afe9f00-b130-11e9-97c7-82421f35d17d.png)

![image](https://user-images.githubusercontent.com/318490/62005345-2c3a2500-b132-11e9-8b56-54c8d535be14.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu .
 - Version: 19.04

**Client (please complete the following information):**
 - Version: tested v0.4.2 and current master

**Additional context**

N/A

**Comment by pdecat** [comment]
This is caused by the `-` characters used in the `googlephotos-uploader-go-api` service name that are encoded as `_2d` leading to a collection name `googlephotos_2duploader_2dgo_2dapi`.

When the [collections are searched, it then compares](https://github.com/99designs/keyring/blob/v1.1.0/libsecret.go#L75) `"/org/freedesktop/secrets/collection/googlephotos_2duploader_2dgo_2dapi"` to `"/org/freedesktop/secrets/collection/googlephotos_uploader_go_api"` which never matches and will then end up creating a new collection.

Removing the `-` characters in the service name resolves the issue:

```
diff --git a/datastore/tokenstore/interface.go b/datastore/tokenstore/interface.go
index 37b3c75..16bfb88 100644
--- a/datastore/tokenstore/interface.go
+++ b/datastore/tokenstore/interface.go
@@ -17,7 +17,7 @@ var (
 )
 
 const (
-       serviceName = "googlephotos-uploader-go-api"
+       serviceName = "googlephotosuploadergoapi"
 )
 
 type TokenManager interface {
```

**Comment by pacoorozco** [comment]
Wow! Good finding... I was trying to look for the root cause... I've see your PR #98, see my comment there that suggest a shorter `serviceName = gPhotosUploader`.
